wandb_version: 1

task:
  desc: null
  value:
    name: ArrayRobot
    physics_engine: physx
    ori_obs: false
    fixed_init: false
    dct:
      order: 3
      step: 0.5
      dim_local: 5
    goal:
      pos:
      - 0.26
      - 0.26
      - 0.09
      ori:
      - 0.0
      - 0.0
      - 0.0
      - 1.0
    reward:
      trans_diff_factor: 0.1
      trans_delta_diff_factor: 100
      reach_threshold: 0.02
      reach_bonus: 10
    env:
      numEnvs: 16
      maxEpisodeLength: 100
      actionSpeedScale: 1
      numActions: 6
      clipActions: 1
      controlFrequencyInv: 2
      robot:
        row_gap: 0.02
        velocity: 0.05
        stiffness: 4000.0
        damping: 200.0
        effort: 1000.0
      object:
        x: 0.09
        y: 0.09
        z: 0.08
      assets:
        force_threshold: 0.005
        robot:
          root: TableBot/urdf
          file: tablebot_row_16.urdf
        object:
          root: egad/eval
          half_extend: 0.04
    sim:
      dt: 0.1
      substeps: 5
      up_axis: z
      use_gpu_pipeline: false
      gravity:
      - 0.0
      - 0.0
      - -9.81
      physx:
        num_threads: 1
        solver_type: 1
        use_gpu: false
        num_position_iterations: 8
        num_velocity_iterations: 0
        contact_offset: 0.0005
        rest_offset: 0.0001
        bounce_threshold_velocity: 0.2
        max_depenetration_velocity: 1000.0
        default_buffer_size_multiplier: 5.0
        max_gpu_contact_pairs: 33554432
        num_subscenes: 16
        contact_collection: 1
    task:
      randomize: false
train:
  desc: null
  value:
    seed: 0
    algo: PPO
    network:
      mlp:
        units:
        - 256
        - 256
        - 128
      separate_value_mlp: true
    ppo:
      name: ArrayRobot
      multi_gpu: false
      normalize_input: true
      normalize_value: true
      value_bootstrap: true
      num_actors: 16
      reward_scale_value: 0.1
      clip_value_loss: false
      normalize_advantage: true
      gamma: 0.99
      tau: 0.95
      learning_rate: 0.0003
      lr_schedule: kl
      kl_threshold: 0.008
      save_best_after: 500
      save_frequency: 200
      grad_norm: 1.0
      entropy_coef: 0.0
      truncate_grads: true
      e_clip: 0.2
      horizon_length: 16
      minibatch_size: 256
      mini_epochs: 8
      critic_coef: 4
      clip_value: true
      bounds_loss_coef: 0.0001
      max_agent_steps: 1000000
task_name:
  desc: null
  value: ArrayRobot
experiment:
  desc: null
  value: ''
num_envs:
  desc: null
  value: 16
num_actions:
  desc: null
  value: 6
seed:
  desc: null
  value: 0
torch_deterministic:
  desc: null
  value: false
sim_device:
  desc: null
  value: cpu
rl_device:
  desc: null
  value: cuda:0
graphics_device_id:
  desc: null
  value: 0
test:
  desc: null
  value: false
checkpoint:
  desc: null
  value: ''
output_name:
  desc: null
  value: lift-freq-6-seed-0
wandb_mode:
  desc: null
  value: online
wandb_entity:
  desc: null
  value: zhengrong
wandb_project:
  desc: null
  value: simple-mani
headless:
  desc: null
  value: false
_wandb:
  desc: null
  value:
    python_version: 3.8.16
    cli_version: 0.14.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1685185935.757966
    t:
      1:
      - 1
      - 50
      - 55
      2:
      - 1
      - 50
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.8.16
      5: 0.14.2
      8:
      - 5
